### PR TITLE
Allow our users to report bugs that also exist in the official SDK here

### PR DESCRIPTION
**Pull request by ItsHarper**
We can't ask users to reproduce their bug on the official version just to submit a bug report to somebody, and we can't ask FIRST to troubleshoot an issue that could be with our code.

### CODE REVIEW

**Comment by ItsHarper** [comment]
@WardBenjamin you put that part in there originally, so I'd like to hear if you still think it should be there.

**Comment by WardBenjamin** [comment]
For reference, what I originally added was:

```
Make sure that your bug is specific to the OpenFTC SDK. If the bug still occurs while using the official FTC SDK, your bug report should be reported to the [official SDK](https://github.com/ftctechnh/ftc_app).
```

I think you're right that we don't want users to have to reproduce on the official version, but a lot of issues might be difficult for us to verify on our own (especially if they're related to hardware external to the phone). 

In my opinion, it'd be okay if they could open an issue here, and if we could verify that it was an issue with the official app we could just mark the issue with a `official SDK problem` label, or something like that, and link it to an issue on ftc_app.

**Comment by Windwoes** [comment]
Hmm, I don't know about this one... I'm torn. Our users will most likely know what they're doing and be able to file helpful bug reports that aren't just noise that can be answered with "disable instant run". So I feel like for a technical user, being able to reproduce on the official SDK in order to send that nice bug report to FIRST wouldn't be too much to ask. I don't feel like we know the SDK internals well enough to fix any serious bugs.

**Comment by ItsHarper** [comment]
> So I feel like for a technical user, being able to reproduce on the official SDK in order to send that nice bug report to FIRST wouldn't be too much to ask.

I thought of that, but what if they just can't reproduce it consistently at all? Some bugs are like that (like the one I mention further down). In addition, cloning the official SDK and copying your OpModes is a somewhat lengthy process, that I'm afraid will make users shy away from submitting reports at all. 

The way I see it, I'd rather hear about an issue than not. As @WardBenjamin says, if we're pretty sure our code shouldn't be causing the problem, or we ourselves can reproduce the issue on the official SDK, we can always post on their issues page ourselves.

> I don't feel like we know the SDK internals well enough to fix any serious bugs.

I'm actually already feeling decently comfortable with the codebase. I spent a lot of time today trying to get to the bottom of [this issue](https://github.com/ftctechnh/ftc_app/issues/411). Assuming it's not actually a firmware issue with the REV hub, I think I had an OK chance of fixing it, if only the issue didn't go away. I pushed a little bit of extra logging to master, in case someone using OpenFTC comes across it. Regardless though, any issues confirmed to be with the official SDK will absolutely be reported there as well.

**Review by Windwoes — APPROVED** [review]

**Comment by Windwoes** [comment]
Fair enough

**Pull request merged**
