### PR TITLE
New icon

### PR DESCRIPTION
**Pull request by Windwoes**
It's not the greatest, but it's something

### CODE REVIEW

**Comment by WardBenjamin** [comment]
Just as a note, this PR does share duplicate commits with https://github.com/OpenFTC/OpenFTC-app/pull/20. In the future, you may wish to branch from the master branch instead of another feature branch.

It might not an issue in this case, but just a note for the future.

**Comment by Windwoes** [comment]
Thanks; I had already noticed that and discussed it with Noah. He said it isn't an issue since he's planning on merging #20 anyway

**Comment by ItsHarper** [comment]
This looks a lot better than I expected at the size it's displayed at in the launcher. I quite like it! My biggest complaint is that it reads more like "FTC Open" to me. Not actually complaining though, thanks so much for taking care of this so quickly!

**Review by ItsHarper — APPROVED** [review]
Great work on the Driver Station detection as well.

**Pull request merged**
